/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporter;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author jucazuse
 */
public final class Interfaz extends javax.swing.JFrame {
    
    public int contador=1;
    public int annoNaci;
    public int edad;
    public String sexo;
    public String line;
    FileWriter fichero = null;
    PrintWriter pw = null;
    String fila;
    String []posiciones;
    /*la he puesto asi o tambien le coloco el getFile pero da igual 
     * no me sale error pero no deja cargar el archivo */
    File file = new File("C:/Users/jucazuse/Documents/NetBeansProjects/TrabajoGID/src/archivo/registro.txt"); 
    Calendar annoSistema = new GregorianCalendar();
    /*esta variable es el año del sistema */
    int anno = annoSistema.get(Calendar.YEAR);
    DefaultTableModel modeloTabla;
    String[] rowfields;
    public String tipoDoc, documento, nombre, apellido,
            fechaNaci, edad1, genero, ciudadRe, ePS;
    
    
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        llenarCbIdentificacion();
        llenarCbCiudadResidencia();
        llenarCbEPS();
        cargarTabla();

  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        cbIdentificacion = new javax.swing.JComboBox();
        jDateFecha = new com.toedter.calendar.JDateChooser();
        cbCiudadR = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        rbFemenino = new javax.swing.JRadioButton();
        rbMasculino = new javax.swing.JRadioButton();
        cbEPS = new javax.swing.JComboBox();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTRegistro = new javax.swing.JTable();
        btnInforme = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 255)));

        jLabel1.setText("Tipo Identificacion");
        jLabel1.setBounds(20, 24, 100, 20);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setText("Nombre");
        jLabel2.setBounds(20, 70, 90, 14);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setText("Fecha Nacimiento");
        jLabel3.setBounds(20, 120, 110, 14);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnGuardar.setText("Guardar Usuario");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnGuardarMouseReleased(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        btnGuardar.setBounds(20, 230, 130, 30);
        jLayeredPane1.add(btnGuardar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cbIdentificacion.setBounds(170, 20, 180, 30);
        jLayeredPane1.add(cbIdentificacion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDateFecha.setBounds(170, 110, 180, 30);
        jLayeredPane1.add(jDateFecha, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cbCiudadR.setBounds(170, 160, 180, 30);
        jLayeredPane1.add(cbCiudadR, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setText("Ciudad Residencia");
        jLabel4.setBounds(20, 170, 100, 20);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtNombre.setBounds(170, 60, 180, 30);
        jLayeredPane1.add(txtNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setText("Identificacion");
        jLabel5.setBounds(400, 20, 110, 30);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setText("Apellidos");
        jLabel6.setBounds(400, 60, 90, 30);
        jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setText("Sexo");
        jLabel7.setBounds(400, 110, 80, 30);
        jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setText("EPS");
        jLabel8.setBounds(400, 160, 50, 30);
        jLayeredPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdentificacionKeyReleased(evt);
            }
        });
        txtIdentificacion.setBounds(510, 20, 190, 30);
        jLayeredPane1.add(txtIdentificacion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtApellidos.setBounds(510, 60, 190, 30);
        jLayeredPane1.add(txtApellidos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(rbFemenino);
        rbFemenino.setText("Femenino");
        rbFemenino.setBounds(510, 110, 80, 23);
        jLayeredPane1.add(rbFemenino, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(rbMasculino);
        rbMasculino.setText("Masculino");
        rbMasculino.setBounds(610, 110, 80, 23);
        jLayeredPane1.add(rbMasculino, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cbEPS.setBounds(510, 160, 190, 30);
        jLayeredPane1.add(cbEPS, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado Usuarios"));

        jLabel9.setText("Buscar Usuarios por Cedula");
        jLabel9.setBounds(10, 30, 160, 30);
        jLayeredPane2.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Tipo Identificacion", "Identificacion", "Nombre", "Apellido", "Fecha Nacimiento", "Edad", "Sexo", "Ciudad Residencia", "EPS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTRegistro);

        jScrollPane2.setBounds(10, 70, 1080, 120);
        jLayeredPane2.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnInforme.setText("Informe de Usuario");
        btnInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformeActionPerformed(evt);
            }
        });
        btnInforme.setBounds(20, 260, 160, 30);
        jLayeredPane2.add(btnInforme, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });
        txtBuscar.setBounds(170, 30, 190, 30);
        jLayeredPane2.add(txtBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1094, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        /*esta variable captura el año de nacimiento */
        annoNaci = jDateFecha.getCalendar().get(Calendar.YEAR);

        /*esta variable nos muestra la edad*/
        edad = (anno - annoNaci);


        /*Aqui obtenemos la fecha del JDateChooser y le damos 
         * formato*/
        Date date = jDateFecha.getDate();
        SimpleDateFormat dt = new SimpleDateFormat("dd/MMM/yyyy");

        /*este es una condicion con operadores ternarios para ver el sexo  */
        sexo = (rbMasculino.isSelected()) ? "Masculino" : "Femenino";

        /*con esto le damos el modelo a la tabla */
        modeloTabla = (DefaultTableModel) jTRegistro.getModel();
       
         /* con esto llenamos la tabla  */
        Object nuevo[] = {
            contador++,cbIdentificacion.getSelectedItem(), txtIdentificacion.getText(), txtNombre.getText(),
            txtApellidos.getText(), dt.format(date), edad, sexo,
            cbCiudadR.getSelectedItem(), cbEPS.getSelectedItem()
        };

        /*con esto añadimos los datos a la tabla */
        modeloTabla.addRow(nuevo);
             
        /*metodo para guardar el archivo */
        guardarArchivo(";", file);
        
        txtIdentificacion.setText("");
        txtNombre.setText("");
        txtApellidos.setText("");

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformeActionPerformed
    
        generarReporte();

    }//GEN-LAST:event_btnInformeActionPerformed

    private void txtIdentificacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionKeyReleased
      leerArchivo();
    }//GEN-LAST:event_txtIdentificacionKeyReleased

    private void btnGuardarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseReleased
       btnGuardar.setEnabled(true);
    }//GEN-LAST:event_btnGuardarMouseReleased

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
       compararDocumento();
    }//GEN-LAST:event_txtBuscarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInforme;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbCiudadR;
    private javax.swing.JComboBox cbEPS;
    private javax.swing.JComboBox cbIdentificacion;
    private com.toedter.calendar.JDateChooser jDateFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTRegistro;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private void llenarCbIdentificacion() {
        cbIdentificacion.addItem("Cedula");
        cbIdentificacion.addItem("Tarjeta Identidad");
        cbIdentificacion.addItem("NN");
    }

    private void llenarCbCiudadResidencia() {
        cbCiudadR.addItem("Alcala");
        cbCiudadR.addItem("Andalucia");
        cbCiudadR.addItem("Buenaventura");
        cbCiudadR.addItem("Buga");
        cbCiudadR.addItem("Caicedonia");
        cbCiudadR.addItem("Cali");
        cbCiudadR.addItem("Cartago");
        cbCiudadR.addItem("Guacari");
        cbCiudadR.addItem("Jamundi");
        cbCiudadR.addItem("Palmira");
        cbCiudadR.addItem("Sevilla");
        cbCiudadR.addItem("Tulua");
        cbCiudadR.addItem("Yumbo");
    }

    private void llenarCbEPS() {
        cbEPS.addItem("Saludcoop");
        cbEPS.addItem("Coomeva");
        cbEPS.addItem("Quiron");
        cbEPS.addItem("Emssanar");
        cbEPS.addItem("Casur");
        cbEPS.addItem("Cosmited");
    }

    private void guardarArchivo(String t, File file) {
        
        /*esta es la fecha del jDateChooser */
        Date date = jDateFecha.getDate();
        SimpleDateFormat dt = new SimpleDateFormat("dd/MMM/yyyy");

        //se separa el texto cada salto de linea
        StringTokenizer st = new StringTokenizer(t, "/n");

        try {
            fichero = new FileWriter(file, true);
            pw = new PrintWriter(fichero);
            //se guarda linea por linea en el archivo
            while (st.hasMoreTokens()) {
                line = st.nextToken();
                pw.print(cbIdentificacion.getSelectedItem());
                pw.print(";");
                pw.print(txtIdentificacion.getText());
                pw.print(";");
                pw.print(txtNombre.getText());
                pw.print(";");
                pw.print(txtApellidos.getText());
                pw.print(";");
                pw.print(dt.format(date));
                pw.print(";");
                pw.print(edad);
                pw.print(";");
                pw.print(sexo);
                pw.print(";");
                pw.print(cbCiudadR.getSelectedItem());
                pw.print(";");
                pw.print(cbEPS.getSelectedItem());
                pw.print(";");
                pw.println();
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (null != fichero) {
                    fichero.close();
                }
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        }
    }

    public void leerArchivo() {
        try {
            Scanner scan = new Scanner(new File("C:/Users/jucazuse/Documents/NetBeansProjects/TrabajoGID/src/archivo/registro.txt"));
            while (scan.hasNext()) {
                fila = scan.nextLine();
                fila = fila.replace(", ", ","); //Quitamos los espacios en blanco despues de la coma 
                posiciones = fila.split(";");
                for (int i = 0; i < posiciones.length; i++) {
                    if (posiciones[i].contentEquals(txtIdentificacion.getText())) {
                        JOptionPane.showMessageDialog(this, "El Numero de Cedula ya Esta Registrado",
                                ("Validacion"), JOptionPane.INFORMATION_MESSAGE);
                        btnGuardar.setEnabled(false);
                        txtIdentificacion.setText("");
                    }

                }
                posiciones = null;
            }
        } catch (FileNotFoundException x) {
            System.out.println("No se pudo encontrar el archivo");
        }
    }


    
     public void cargarTabla() {
        try {
            modeloTabla = (DefaultTableModel) jTRegistro.getModel();
            Scanner scan = new Scanner(new File("C:/Users/jucazuse/Documents/NetBeansProjects/TrabajoGID/src/archivo/registro.txt"));
            while (scan.hasNext()) {
                fila = scan.nextLine();
                fila = fila.replace(", ", ","); //Quitamos los espacios en blanco despues de la coma 
                posiciones = fila.split(";");
                tipoDoc=posiciones[0];
                documento=posiciones[1];
                nombre=posiciones[2];
                apellido=posiciones[3];
                fechaNaci=posiciones[4];
                edad1=posiciones[5];
                genero=posiciones[6];
                ciudadRe=posiciones[7];
                ePS=posiciones[8];
                Object[] tabla={contador++,tipoDoc,documento,nombre,apellido,
                                fechaNaci,edad1,genero,ciudadRe,ePS};
                modeloTabla.addRow(tabla);
                posiciones = null;
            }
        } catch (FileNotFoundException x) {
            System.out.println("No se pudo encontrar el archivo");
        }
    }
     
     
    public void compararDocumento() {
        try {
            Scanner scan = new Scanner(new File("C:/Users/jucazuse/Documents/NetBeansProjects/TrabajoGID/src/archivo/registro.txt"));
            while (scan.hasNext()) {
                fila = scan.nextLine();
                fila = fila.replace(", ", ","); //Quitamos los espacios en blanco despues de la coma 
                posiciones = fila.split(";");
                documento = posiciones[1];
                nombre = posiciones[2];
                apellido = posiciones[3];
                if (txtBuscar.getText().equals(documento)) {
                    JOptionPane.showMessageDialog(this, "El Usuario esta Registrado con el Nombre de:  ".concat(nombre).concat(" ")
                            .concat(apellido), "Informacion", JOptionPane.INFORMATION_MESSAGE);
                    txtBuscar.setText("");

                }
                posiciones = null;
            }

        } catch (FileNotFoundException x) {
            System.out.println("No se pudo encontrar el archivo");
        }

    }

    public void generarReporte() {
        try {
            try {
                
                Scanner scan = new Scanner(new File("C:/Users/jucazuse/Documents/NetBeansProjects/TrabajoGID/src/archivo/registro.txt"));
                while (scan.hasNext()) {
                    fila = scan.nextLine();
                    fila = fila.replace(", ", ","); //Quitamos los espacios en blanco despues de la coma 
                    posiciones = fila.split(";");
                    Metodos metodo = new Metodos();
                    Datos datos = new Datos(posiciones[0], posiciones[1], posiciones[2], posiciones[3], posiciones[4], posiciones[5], posiciones[6], posiciones[7], posiciones[8]);

                    metodo.addDatos(datos);
                    URL url = this.getClass().getResource("/archivo/registrados.jasper");
                    JasperReport reporte = (JasperReport) JRLoader.loadObject(url);
                    JasperPrint jasperPrint = JasperFillManager.fillReport(reporte, null, metodo);
                    JRExporter exporter = new JRPdfExporter();
                    exporter.setParameter(JRExporterParameter.JASPER_PRINT, jasperPrint);
                    exporter.setParameter(JRExporterParameter.OUTPUT_FILE, new java.io.File("Registrados.pdf"));
                    exporter.exportReport();
                    JasperViewer viewer = new JasperViewer(jasperPrint);
                    viewer.setTitle("Registrados");
                    viewer.setVisible(true);
                    posiciones = null;
                }

            } catch (FileNotFoundException x) {
                System.out.println("No se pudo encontrar el archivo");
            }

        } catch (JRException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);

        }
    }
}
